services:
  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    ports:
      - 3000:3000
    environment:
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
    restart: unless-stopped
